version: '3.8'
services:
  app:
    build: .
    container_name: app-backend
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://user:password@app-postgres:5432/mydb?schema=public'
    depends_on:
      - db
    networks:
      nestjs:
  db:
    image: postgres:13
    container_name: app-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      nestjs:
volumes:
  postgres_data:

networks:
  nestjs:
    driver: bridge
